2022-10-29 18:31:17.853464: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-10-29 18:31:18.414638: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 15401 MB memory:  -> device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:84:00.0, compute capability: 6.0
2022-10-29 18:31:23.706017: E tensorflow/stream_executor/cuda/cuda_dnn.cc:377] Loaded runtime CuDNN library: 8.0.5 but source was compiled with: 8.1.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
2022-10-29 18:31:23.706771: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at cudnn_rnn_ops.cc:1553 : UNKNOWN: Fail to find the dnn implementation.
Traceback (most recent call last):
  File "main.py", line 370, in <module>
    main()
  File "main.py", line 246, in main
    dict_ensemble = evaluate_ga('/csv/' + name[:-4] + '.csv', labels, train_data, test_data, sys.argv[3])
  File "/mnt/campus/math/cluster/research/slurm-pr1/work_root/mmalekis/MVVGE/src/ga/evaluate_ga.py", line 534, in evaluate_ga
    train_MC_predict_var_rnn_reduction, anomalies_rnn_reduction, precision_rnn_reduction, recall_rnn_reduction, Accuracy_rnn_reduction, F1_rnn_reduction = evaluate_rnn(
  File "/mnt/campus/math/cluster/research/slurm-pr1/work_root/mmalekis/MVVGE/src/evaluation/evaluation.py", line 843, in evaluate_rnn
    model.fit(train_x, train_y, epochs=rnn_epochs, verbose=2)
  File "/work/mmalekis/.conda/envs/gennn/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/work/mmalekis/.conda/envs/gennn/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 54, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.UnknownError: Graph execution error:

Fail to find the dnn implementation.
	 [[{{node CudnnRNN}}]]
	 [[sequential/lstm/PartitionedCall]] [Op:__inference_train_function_7466]
